### ISSUE TITLE
Move and Link Present-at-DevCoP

### ISSUE THREAD

**Issue by s-laugh** [esdc-devcop/guides#11]
The https://github.com/esdc-devcop/guides/blob/master/Present-at-DevCoP.md Should be moved under a folder for it's category. It should also get linked from the README.md.

**Comment by s-laugh** [comment]
The commit was also broken and has been rolled back onto https://github.com/esdc-devcop/guides/tree/ahmadsBrokenBranch

**Comment by ahmad-shahid** [comment]
done (commit 65c8e08)
